apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: aspnetcore-ddd
    service: webapi
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    service: webapi
